language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.4

env:
  - DB=mysql

services:
  - redis-server

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids tmp/files tmp/reports tmp/snapshots
  - cd frontend && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec teaspoon
  - CODECLIMATE_REPO_TOKEN=2fe327f67e242f98cc9a5d6ef1629d5289983acd445e35d5b5f44cd3979a71a1 codeclimate < ./coverage/default/lcov.info

env:
  global:
    secure: I7KspoNlLUt6d/EuxHixFzeEmmyS7C8oABXvSshwivrolPeylGJn3yRyzkTsk86pCBeAssDD/ozAVde2XrPDDpmcXZPvBZz7S1YZj4Wt7MHdOlHMT8zujx/+HQaz07Yy7efjoTF7MJNegn0nbh9+pNhx/o/GF+FIDEGX3bLEY58=

addons:
  code_climate:
    repo_token: 2fe327f67e242f98cc9a5d6ef1629d5289983acd445e35d5b5f44cd3979a71a1

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
